apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: prowlarr
description: prowlarr helm chart for Kubernetes
type: application
version: 0.3.0
# image: ghcr.io/onedr0p/prowlarr
appVersion: "1.17.2"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/radarr
home: https://github.com/prowlarr/prowlarr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
